name: CI pipeline

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    lint-and-test:
        runs-on: windows-latest
        strategy:
            matrix:
                python-version: ["3.12"]
        steps:
            - uses: actions/checkout@v5
            - name: install uv
              uses: astral-sh/setup-uv@v5
              with:
                python-version: ${{matrix.python-version}}
                enable-cache: true
            - name: install dependencies
              run: uv sync
            - name: lint
              run: make lint
            - name: format
              run: make format
            - name: test
              run: make test
            
            - name: build executable with PyInstaller
              run: >
                 uv run pyinstaller --onefile --windowed
                 --name "EMV-TLV-Parser"
                 --add-data "src/emv_tlv/dictionaries;emv_tlv/dictionaries"
                 --path src gui/app.py
            - name: upload executable
              uses: actions/upload-artifact@v4
              with:
                 name: EMV-TLV-Parser
                 path: dist/EMV-TLV-Parser.exe
            


    